/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EjerciciosRouteImport } from './routes/ejercicios'
import { Route as EntrenarRouteImport } from './routes/entrenar'
import { Route as InformeRouteImport } from './routes/informe'
import { Route as NutricionRouteImport } from './routes/nutricion'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PerfilRouteImport } from './routes/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EjerciciosRoute = EjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenarRoute = EntrenarRouteImport.update({
  id: '/entrenar',
  path: '/entrenar',
  getParentRoute: () => rootRouteImport,
} as any)
const InformeRoute = InformeRouteImport.update({
  id: '/informe',
  path: '/informe',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricionRoute = NutricionRouteImport.update({
  id: '/nutricion',
  path: '/nutricion',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenar': typeof EntrenarRoute
  '/informe': typeof InformeRoute
  '/nutricion': typeof NutricionRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenar': typeof EntrenarRoute
  '/informe': typeof InformeRoute
  '/nutricion': typeof NutricionRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenar': typeof EntrenarRoute
  '/informe': typeof InformeRoute
  '/nutricion': typeof NutricionRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ejercicios'
    | '/entrenar'
    | '/informe'
    | '/nutricion'
    | '/onboarding'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ejercicios'
    | '/entrenar'
    | '/informe'
    | '/nutricion'
    | '/onboarding'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/ejercicios'
    | '/entrenar'
    | '/informe'
    | '/nutricion'
    | '/onboarding'
    | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EjerciciosRoute: typeof EjerciciosRoute
  EntrenarRoute: typeof EntrenarRoute
  InformeRoute: typeof InformeRoute
  NutricionRoute: typeof NutricionRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios': {
      id: '/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof EjerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenar': {
      id: '/entrenar'
      path: '/entrenar'
      fullPath: '/entrenar'
      preLoaderRoute: typeof EntrenarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informe': {
      id: '/informe'
      path: '/informe'
      fullPath: '/informe'
      preLoaderRoute: typeof InformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricion': {
      id: '/nutricion'
      path: '/nutricion'
      fullPath: '/nutricion'
      preLoaderRoute: typeof NutricionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EjerciciosRoute: EjerciciosRoute,
  EntrenarRoute: EntrenarRoute,
  InformeRoute: InformeRoute,
  NutricionRoute: NutricionRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
